#!/usr/bin/env bash
set -euo pipefail

COMPOSE_FILE="${COMPOSE_FILE:-infra/docker-compose.yml}"
WAIT_SECONDS="${WAIT_SECONDS:-120}"

ts() { date '+%Y-%m-%d %H:%M:%S'; }
log() { echo "[$(ts)] $*"; }
fail() { log "ERRO: $*"; exit 1; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "Dependencia nao encontrada: $1"
}

need_cmd docker
need_cmd curl
need_cmd openssl

JWT_SECRET="${JWT_SECRET:-$(openssl rand -base64 48)}"
SEED_PACIENTE_LOGIN_1="${SEED_PACIENTE_LOGIN_1:-pac_$(date +%s)}"
SEED_PACIENTE_ID_1="${SEED_PACIENTE_ID_1:-1}"
SEED_PACIENTE_LOGIN_2="${SEED_PACIENTE_LOGIN_2:-pac_$(date +%s)_2}"
SEED_PACIENTE_ID_2="${SEED_PACIENTE_ID_2:-2}"

AUTH_SEED_PACIENTE_LOGIN="${AUTH_SEED_PACIENTE_LOGIN:-$SEED_PACIENTE_LOGIN_1}"
AUTH_SEED_PACIENTE_SENHA="${AUTH_SEED_PACIENTE_SENHA:-$(openssl rand -hex 8)}"
AUTH_SEED_PACIENTE_TIPO="${AUTH_SEED_PACIENTE_TIPO:-PACIENTE}"
AUTH_SEED_PROF_LOGIN="${AUTH_SEED_PROF_LOGIN:-prof_$(date +%s)}"
AUTH_SEED_PROF_SENHA="${AUTH_SEED_PROF_SENHA:-$(openssl rand -hex 8)}"
AUTH_SEED_PROF_TIPO="${AUTH_SEED_PROF_TIPO:-PROFISSIONAL}"

RABBITMQ_EXCHANGE_EVENTS="${RABBITMQ_EXCHANGE_EVENTS:-farma.events}"
RABBITMQ_QUEUE_MEDICATION_CREATED="${RABBITMQ_QUEUE_MEDICATION_CREATED:-safety.medication.created}"
RABBITMQ_QUEUE_MEDICATION_CREATED_DLQ="${RABBITMQ_QUEUE_MEDICATION_CREATED_DLQ:-safety.medication.created.dlq}"
RABBITMQ_ROUTING_MEDICATION_CREATED="${RABBITMQ_ROUTING_MEDICATION_CREATED:-medication.created}"
RABBITMQ_ROUTING_MEDICATION_CREATED_DLQ="${RABBITMQ_ROUTING_MEDICATION_CREATED_DLQ:-safety.medication.created.dlq}"
RABBITMQ_ROUTING_SAFETY_ALERT_CREATED="${RABBITMQ_ROUTING_SAFETY_ALERT_CREATED:-safety.alert.created}"
RABBITMQ_QUEUE_ALERT_CREATED="${RABBITMQ_QUEUE_ALERT_CREATED:-patient.safety.alert.created}"
RABBITMQ_QUEUE_ALERT_CREATED_DLQ="${RABBITMQ_QUEUE_ALERT_CREATED_DLQ:-patient.safety.alert.created.dlq}"
RABBITMQ_ROUTING_ALERT_CREATED="${RABBITMQ_ROUTING_ALERT_CREATED:-safety.alert.created}"
RABBITMQ_ROUTING_ALERT_CREATED_DLQ="${RABBITMQ_ROUTING_ALERT_CREATED_DLQ:-patient.safety.alert.created.dlq}"
RABBITMQ_QUEUE_PRESCRIPTION_CREATED="${RABBITMQ_QUEUE_PRESCRIPTION_CREATED:-adherence.medication.prescription.created}"
RABBITMQ_QUEUE_PRESCRIPTION_CREATED_DLQ="${RABBITMQ_QUEUE_PRESCRIPTION_CREATED_DLQ:-adherence.medication.prescription.created.dlq}"
RABBITMQ_ROUTING_PRESCRIPTION_CREATED="${RABBITMQ_ROUTING_PRESCRIPTION_CREATED:-medication.prescription.created}"
RABBITMQ_ROUTING_PRESCRIPTION_CREATED_COMPAT="${RABBITMQ_ROUTING_PRESCRIPTION_CREATED_COMPAT:-medication.created}"
RABBITMQ_ROUTING_PRESCRIPTION_CREATED_DLQ="${RABBITMQ_ROUTING_PRESCRIPTION_CREATED_DLQ:-adherence.medication.prescription.created.dlq}"
RABBITMQ_ROUTING_DOSE_REGISTERED="${RABBITMQ_ROUTING_DOSE_REGISTERED:-adherence.dose.registered}"

log "Limpando stack anterior..."
docker compose -f "$COMPOSE_FILE" down -v >/dev/null 2>&1 || true

log "Subindo stack FarmaSUS..."
JWT_SECRET="$JWT_SECRET" \
SEED_PACIENTE_LOGIN_1="$SEED_PACIENTE_LOGIN_1" \
SEED_PACIENTE_ID_1="$SEED_PACIENTE_ID_1" \
SEED_PACIENTE_LOGIN_2="$SEED_PACIENTE_LOGIN_2" \
SEED_PACIENTE_ID_2="$SEED_PACIENTE_ID_2" \
AUTH_SEED_PACIENTE_LOGIN="$AUTH_SEED_PACIENTE_LOGIN" \
AUTH_SEED_PACIENTE_SENHA="$AUTH_SEED_PACIENTE_SENHA" \
AUTH_SEED_PACIENTE_TIPO="$AUTH_SEED_PACIENTE_TIPO" \
AUTH_SEED_PROF_LOGIN="$AUTH_SEED_PROF_LOGIN" \
AUTH_SEED_PROF_SENHA="$AUTH_SEED_PROF_SENHA" \
AUTH_SEED_PROF_TIPO="$AUTH_SEED_PROF_TIPO" \
RABBITMQ_EXCHANGE_EVENTS="$RABBITMQ_EXCHANGE_EVENTS" \
RABBITMQ_QUEUE_MEDICATION_CREATED="$RABBITMQ_QUEUE_MEDICATION_CREATED" \
RABBITMQ_QUEUE_MEDICATION_CREATED_DLQ="$RABBITMQ_QUEUE_MEDICATION_CREATED_DLQ" \
RABBITMQ_ROUTING_MEDICATION_CREATED="$RABBITMQ_ROUTING_MEDICATION_CREATED" \
RABBITMQ_ROUTING_MEDICATION_CREATED_DLQ="$RABBITMQ_ROUTING_MEDICATION_CREATED_DLQ" \
RABBITMQ_ROUTING_SAFETY_ALERT_CREATED="$RABBITMQ_ROUTING_SAFETY_ALERT_CREATED" \
RABBITMQ_QUEUE_ALERT_CREATED="$RABBITMQ_QUEUE_ALERT_CREATED" \
RABBITMQ_QUEUE_ALERT_CREATED_DLQ="$RABBITMQ_QUEUE_ALERT_CREATED_DLQ" \
RABBITMQ_ROUTING_ALERT_CREATED="$RABBITMQ_ROUTING_ALERT_CREATED" \
RABBITMQ_ROUTING_ALERT_CREATED_DLQ="$RABBITMQ_ROUTING_ALERT_CREATED_DLQ" \
RABBITMQ_QUEUE_PRESCRIPTION_CREATED="$RABBITMQ_QUEUE_PRESCRIPTION_CREATED" \
RABBITMQ_QUEUE_PRESCRIPTION_CREATED_DLQ="$RABBITMQ_QUEUE_PRESCRIPTION_CREATED_DLQ" \
RABBITMQ_ROUTING_PRESCRIPTION_CREATED="$RABBITMQ_ROUTING_PRESCRIPTION_CREATED" \
RABBITMQ_ROUTING_PRESCRIPTION_CREATED_COMPAT="$RABBITMQ_ROUTING_PRESCRIPTION_CREATED_COMPAT" \
RABBITMQ_ROUTING_PRESCRIPTION_CREATED_DLQ="$RABBITMQ_ROUTING_PRESCRIPTION_CREATED_DLQ" \
RABBITMQ_ROUTING_DOSE_REGISTERED="$RABBITMQ_ROUTING_DOSE_REGISTERED" \
docker compose -f "$COMPOSE_FILE" up -d --build

wait_health() {
  local service="$1"
  local url="$2"
  local deadline=$((SECONDS + WAIT_SECONDS))
  while (( SECONDS < deadline )); do
    code="$(curl -s -o /tmp/${service}-health.json -w '%{http_code}' "$url" || true)"
    if [[ "$code" == "200" ]]; then
      log "$service OK ($url)"
      return 0
    fi
    sleep 2
  done
  fail "$service nao ficou saudavel em ate ${WAIT_SECONDS}s. Verifique: docker logs --tail 200 farma-${service}"
}

log "Aguardando health dos servicos..."
wait_health "medication-service" "http://localhost:8080/actuator/health"
wait_health "safety-service" "http://localhost:8081/actuator/health"
wait_health "patient-service" "http://localhost:8082/actuator/health"
wait_health "auth-service" "http://localhost:8083/actuator/health"
wait_health "adherence-service" "http://localhost:8084/actuator/health"

log "Validando login seed no auth-service..."
LOGIN_PAYLOAD="$(printf '{"login":"%s","senha":"%s","tipoUsuario":"%s"}' \
  "$AUTH_SEED_PROF_LOGIN" "$AUTH_SEED_PROF_SENHA" "$AUTH_SEED_PROF_TIPO")"
LOGIN_CODE="$(curl -sS -o /tmp/auth-login.json -w '%{http_code}' \
  -X POST "http://localhost:8083/auth/login" \
  -H 'Content-Type: application/json' \
  -d "$LOGIN_PAYLOAD" || true)"
if [[ "$LOGIN_CODE" != "200" ]]; then
  fail "Login seed falhou no auth-service (HTTP $LOGIN_CODE). Body: $(cat /tmp/auth-login.json 2>/dev/null || true)"
fi

cat > .env.local.generated <<EOF
JWT_SECRET=$JWT_SECRET
SEED_PACIENTE_LOGIN_1=$SEED_PACIENTE_LOGIN_1
SEED_PACIENTE_ID_1=$SEED_PACIENTE_ID_1
SEED_PACIENTE_LOGIN_2=$SEED_PACIENTE_LOGIN_2
SEED_PACIENTE_ID_2=$SEED_PACIENTE_ID_2
AUTH_SEED_PACIENTE_LOGIN=$AUTH_SEED_PACIENTE_LOGIN
AUTH_SEED_PACIENTE_SENHA=$AUTH_SEED_PACIENTE_SENHA
AUTH_SEED_PACIENTE_TIPO=$AUTH_SEED_PACIENTE_TIPO
AUTH_SEED_PROF_LOGIN=$AUTH_SEED_PROF_LOGIN
AUTH_SEED_PROF_SENHA=$AUTH_SEED_PROF_SENHA
AUTH_SEED_PROF_TIPO=$AUTH_SEED_PROF_TIPO
AUTH_LOGIN=$AUTH_SEED_PROF_LOGIN
AUTH_SENHA=$AUTH_SEED_PROF_SENHA
AUTH_TIPO=$AUTH_SEED_PROF_TIPO
PACIENTE_ID=$SEED_PACIENTE_ID_1
EOF

log "Stack pronta."
log "Credenciais profissional para E2E:"
log "  AUTH_LOGIN=$AUTH_SEED_PROF_LOGIN"
log "  AUTH_SENHA=$AUTH_SEED_PROF_SENHA"
log "  AUTH_TIPO=$AUTH_SEED_PROF_TIPO"
log "Arquivo gerado: .env.local.generated"
